/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: miniko (https://sketchfab.com/miniklon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jims-haunted-home-gym-076ee17240054021b1246dbda6ddbbac
Title: Jim's Haunted Home Gym
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const HauntedHouse = (props) => {
  const group = useRef();
  const { nodes, materials, animations, scene } = useGLTF(
    "/jims_haunted_home_gym.glb"
  );
  const { actions, clips } = useAnimations(animations, group);
  const scroll = useScroll();

  useEffect(() => {
    console.log(actions, clips);
    actions["Play"].play().paused = true;
  }, []);

  useFrame(() => {
    actions["Play"].time =
      (actions["Play"].getClip().duration * scroll.offset) / 3;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="889e0ea5a4ee41cbb0f0a3ce5f63a810fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="running_machine" position={[0, 0.136, -0.379]}>
                  <mesh
                    name="running_machine_running_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.running_machine_running_m_0.geometry}
                    material={materials.running_m}
                  />
                </group>
                <group
                  name="dumbbell_set"
                  position={[7.558, 0, -15.229]}
                  rotation={[0, Math.PI / 2, 0]}
                >
                  <group name="rack" position={[0.379, 0, 0]}>
                    <mesh
                      name="rack_weights_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.rack_weights_m_0.geometry}
                      material={materials.weights_m}
                    />
                  </group>
                  <group name="dumbbell" position={[0.379, 0, 0]}>
                    <mesh
                      name="dumbbell_weights_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.dumbbell_weights_m_0.geometry}
                      material={materials.weights_m}
                    />
                  </group>
                </group>
                <group
                  name="yogamat_band"
                  position={[-14.242, -0.953, -12.984]}
                  rotation={[-0.085, 0, -0.001]}
                  scale={1.476}
                >
                  <group
                    name="band"
                    position={[0, 0.324, -0.269]}
                    rotation={[0.034, 0, 0]}
                  >
                    <mesh
                      name="band_yoga_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.band_yoga_m_0.geometry}
                      material={materials.yoga_m}
                    />
                  </group>
                  <group name="yogamat" position={[0, 0.022, -0.256]}>
                    <mesh
                      name="yogamat_yoga_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.yogamat_yoga_m_0.geometry}
                      material={materials.yoga_m}
                    />
                  </group>
                </group>
                <group name="garage_door" position={[-0.672, -0.048, 0.838]}>
                  <mesh
                    name="garage_door_garage_door_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.garage_door_garage_door_m_0.geometry}
                    material={materials.garage_door_m}
                  />
                </group>
                <group
                  name="door"
                  position={[-37.574, 0, -25.422]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                >
                  <group
                    name="top"
                    position={[-30.845, 8.01, -11.617]}
                    rotation={[0, -0.032, 0]}
                  >
                    <mesh
                      name="top_door_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.top_door_m_0.geometry}
                      material={materials.door_m}
                    />
                  </group>
                  <group name="bottom" position={[-32.837, 3.91, -12.618]}>
                    <mesh
                      name="bottom_door_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.bottom_door_m_0.geometry}
                      material={materials.door_m}
                    />
                  </group>
                </group>
                <group name="island" position={[0, 0, -0.379]}>
                  <mesh
                    name="island_sand_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.island_sand_m_0.geometry}
                    material={materials.sand_m}
                  />
                </group>
                <group name="plank_medium">
                  <group name="plank_medium15" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium15_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium15_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium14" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium14_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium14_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium13" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium13_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium13_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium12" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium12_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium12_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium11" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium11_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium11_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium10" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium10_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium10_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium9" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium9_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium9_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium8" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium8_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium8_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium7" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium7_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium7_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium6" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium6_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium6_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium5" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium5_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium5_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium4" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium4_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium4_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium3" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium3_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium3_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium2" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium2_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium2_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium1" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium1_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium1_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_medium_1" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_medium_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_medium_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                </group>
                <group name="plank_small">
                  <group name="plank_small24" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small24_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small24_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small23" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small23_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small23_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small22" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small22_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small22_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small21" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small21_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small21_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small20" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small20_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small20_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small19" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small19_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small19_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small18" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small18_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small18_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small17" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small17_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small17_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small16" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small16_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small16_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small15" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small15_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small15_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small14" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small14_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small14_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small13" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small13_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small13_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small12" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small12_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small12_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small11" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small11_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small11_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small10" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small10_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small10_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small9" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small9_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small9_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small8" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small8_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small8_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small7" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small7_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small7_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small6" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small6_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small6_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small5" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small5_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small5_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small4" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small4_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small4_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small3" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small3_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small3_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small2" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small2_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small2_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small1" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small1_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small1_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_small_1" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_small_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_small_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                </group>
                <group name="cinder_blocks">
                  <group name="cinder_block25" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block25_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block25_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block24" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block24_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block24_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block23" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block23_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block23_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block22" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block22_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block22_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block21" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block21_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block21_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block20" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block20_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block20_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block19" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block19_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block19_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block18" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block18_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block18_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block17" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block17_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block17_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block16" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block16_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block16_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block15" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block15_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block15_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block14" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block14_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block14_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block13" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block13_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block13_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block12" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block12_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block12_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block11" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block11_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block11_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block10" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block10_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block10_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block9" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block9_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block9_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block8" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block8_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block8_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block7" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block7_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block7_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block6" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block6_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block6_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block5" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block5_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block5_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block4" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block4_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block4_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block3" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block3_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block3_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block2" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block2_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block2_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block1" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block1_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block1_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                  <group name="cinder_block" position={[0, 0, -0.379]}>
                    <mesh
                      name="cinder_block_cinder_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.cinder_block_cinder_m_0.geometry}
                      material={materials.cinder_m}
                    />
                  </group>
                </group>
                <group name="plank_large">
                  <group name="plank_large13" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large13_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large13_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_large11" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large11_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large11_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_large12" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large12_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large12_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_large10" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large10_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large10_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_large9" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large9_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large9_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_large8" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large8_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large8_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_large7" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large7_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large7_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_large6" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large6_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large6_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_large5" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large5_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large5_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_large4" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large4_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large4_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_large2" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large2_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large2_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                  <group name="plank_large_1" position={[0, 0, -0.379]}>
                    <mesh
                      name="plank_large_planks_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plank_large_planks_m_0.geometry}
                      material={materials.planks_m}
                    />
                  </group>
                </group>
                <group name="stones">
                  <group name="stone10" position={[0, 0, -0.379]}>
                    <mesh
                      name="stone10_stone_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.stone10_stone_m_0.geometry}
                      material={materials.stone_m}
                    />
                  </group>
                  <group name="stone9" position={[0, 0, -0.379]}>
                    <mesh
                      name="stone9_stone_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.stone9_stone_m_0.geometry}
                      material={materials.stone_m}
                    />
                  </group>
                  <group name="stone8" position={[0, 0, -0.379]}>
                    <mesh
                      name="stone8_stone_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.stone8_stone_m_0.geometry}
                      material={materials.stone_m}
                    />
                  </group>
                  <group name="stone7" position={[0, 0, -0.379]}>
                    <mesh
                      name="stone7_stone_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.stone7_stone_m_0.geometry}
                      material={materials.stone_m}
                    />
                  </group>
                  <group name="stone6" position={[0, 0, -0.379]}>
                    <mesh
                      name="stone6_stone_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.stone6_stone_m_0.geometry}
                      material={materials.stone_m}
                    />
                  </group>
                  <group name="stone5" position={[0, 0, -0.379]}>
                    <mesh
                      name="stone5_stone_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.stone5_stone_m_0.geometry}
                      material={materials.stone_m}
                    />
                  </group>
                  <group name="stone4" position={[0, 0, -0.379]}>
                    <mesh
                      name="stone4_stone_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.stone4_stone_m_0.geometry}
                      material={materials.stone_m}
                    />
                  </group>
                  <group name="stone3" position={[0, 0, -0.379]}>
                    <mesh
                      name="stone3_stone_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.stone3_stone_m_0.geometry}
                      material={materials.stone_m}
                    />
                  </group>
                  <group name="stone2" position={[0, 0, -0.379]}>
                    <mesh
                      name="stone2_stone_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.stone2_stone_m_0.geometry}
                      material={materials.stone_m}
                    />
                  </group>
                  <group name="stone1" position={[0, 0, -0.379]}>
                    <mesh
                      name="stone1_stone_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.stone1_stone_m_0.geometry}
                      material={materials.stone_m}
                    />
                  </group>
                  <group name="stone" position={[0, 0, -0.379]}>
                    <mesh
                      name="stone_stone_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.stone_stone_m_0.geometry}
                      material={materials.stone_m}
                    />
                  </group>
                </group>
                <group name="tiles">
                  <group name="tile" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile1" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile1_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile1_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile2" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile2_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile2_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group
                    name="tile5"
                    position={[-0.011, 0.111, -0.379]}
                    rotation={[0, 0, -0.018]}
                  >
                    <mesh
                      name="tile5_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile5_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile6" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile6_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile6_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile7" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile7_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile7_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile8" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile8_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile8_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile9" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile9_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile9_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile10" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile10_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile10_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile11" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile11_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile11_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile12" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile12_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile12_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile13" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile13_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile13_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile14" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile14_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile14_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile16" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile16_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile16_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile17" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile17_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile17_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile18" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile18_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile18_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile19" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile19_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile19_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile20" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile20_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile20_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group
                    name="tile21"
                    position={[0.024, 0.094, -0.344]}
                    rotation={[-0.051, -0.002, 0.036]}
                  >
                    <mesh
                      name="tile21_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile21_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile22" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile22_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile22_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile25" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile25_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile25_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile27" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile27_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile27_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile28" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile28_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile28_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile29" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile29_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile29_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile30" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile30_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile30_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile31" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile31_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile31_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile32" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile32_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile32_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile33" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile33_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile33_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile34" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile34_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile34_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile35" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile35_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile35_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile37" position={[0.429, 0.11, -0.379]}>
                    <mesh
                      name="tile37_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile37_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group
                    name="tile38"
                    position={[0, -0.497, -0.285]}
                    rotation={[-0.137, 0, 0]}
                  >
                    <mesh
                      name="tile38_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile38_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile39" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile39_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile39_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group
                    name="tile40"
                    position={[-0.187, -0.325, -0.222]}
                    rotation={[-0.149, 0.023, -0.149]}
                  >
                    <mesh
                      name="tile40_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile40_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group
                    name="tile41"
                    position={[-0.75, 0.981, -0.379]}
                    rotation={[0, 0, -0.132]}
                  >
                    <mesh
                      name="tile41_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile41_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile42" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile42_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile42_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile43" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile43_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile43_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile44" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile44_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile44_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile46" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile46_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile46_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile48" position={[0, 0, 2.419]}>
                    <mesh
                      name="tile48_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile48_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile49" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile49_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile49_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile50" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile50_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile50_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile51" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile51_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile51_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile52" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile52_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile52_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile53" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile53_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile53_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile55" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile55_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile55_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile3" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile3_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile3_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile4" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile4_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile4_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile15" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile15_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile15_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile23" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile23_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile23_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile24" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile24_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile24_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile59" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile59_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile59_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile58" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile58_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile58_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile60" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile60_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile60_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile56" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile56_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile56_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile57" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile57_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile57_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile26" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile26_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile26_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile36" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile36_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile36_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile45" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile45_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile45_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile47" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile47_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile47_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                  <group name="tile54" position={[0, 0, -0.379]}>
                    <mesh
                      name="tile54_tiles_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.tile54_tiles_m_0.geometry}
                      material={materials.tiles_m}
                    />
                  </group>
                </group>
                <group
                  name="tree"
                  position={[-32.288, -9.208, -29.731]}
                  rotation={[0, 0.001, 0]}
                  scale={1.006}
                >
                  <mesh
                    name="tree_tree_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.tree_tree_m_0.geometry}
                    material={materials.tree_m}
                  />
                </group>
                <group name="structure">
                  <group name="structure_1" position={[0, 0, -0.379]}>
                    <mesh
                      name="structure_1_structure_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.structure_1_structure_m_0.geometry}
                      material={materials.structure_m}
                    />
                  </group>
                  <group name="structure_2" position={[0, 0, -0.379]}>
                    <mesh
                      name="structure_2_structure_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.structure_2_structure_m_0.geometry}
                      material={materials.structure_m}
                    />
                  </group>
                  <group name="structure_3" position={[0, 0, -0.379]}>
                    <mesh
                      name="structure_3_structure_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.structure_3_structure_m_0.geometry}
                      material={materials.structure_m}
                    />
                  </group>
                  <group name="structure_4" position={[0, 0, -0.379]}>
                    <mesh
                      name="structure_4_structure_m_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.structure_4_structure_m_0.geometry}
                      material={materials.structure_m}
                    />
                  </group>
                </group>
                <group name="brick" position={[0, 0, -0.379]}>
                  <mesh
                    name="brick_bricks_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.brick_bricks_m_0.geometry}
                    material={materials.bricks_m}
                  />
                </group>
                <group name="punching_bag" position={[0, 0, -0.379]}>
                  <mesh
                    name="punching_bag_punching_set_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.punching_bag_punching_set_m_0.geometry}
                    material={materials.punching_set_m}
                  />
                </group>
                <group name="walls" position={[0, 0, -0.379]}>
                  <mesh
                    name="walls_walls_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.walls_walls_m_0.geometry}
                    material={materials.walls_m}
                  />
                </group>
                <group
                  name="barbell"
                  position={[10.418, 2.864, 6.571]}
                  rotation={[-0.003, 0, 0]}
                >
                  <mesh
                    name="barbell_bench_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.barbell_bench_m_0.geometry}
                    material={materials.bench_m}
                  />
                </group>
                <group name="rack_1">
                  <mesh
                    name="rack_bench_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.rack_bench_m_0.geometry}
                    material={materials.bench_m}
                  />
                </group>
                <group
                  name="bench"
                  position={[9.545, 1.034, 5.962]}
                  rotation={[0, -0.002, 0]}
                >
                  <mesh
                    name="bench_bench_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bench_bench_m_0.geometry}
                    material={materials.bench_m}
                  />
                </group>
                <group
                  name="pCylinder3"
                  position={[-1.527, 1.004, 6.682]}
                  rotation={[0.005, 0, -0.018]}
                >
                  <mesh
                    name="pCylinder3_shoe_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder3_shoe_m_0.geometry}
                    material={materials.shoe_m}
                  />
                </group>
                <group name="pCylinder4" position={[3.638, 0.17, 0]}>
                  <mesh
                    name="pCylinder4_shoe_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder4_shoe_m_0.geometry}
                    material={materials.shoe_m}
                  />
                </group>
                <group name="beware">
                  <mesh
                    name="beware_planks_m_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.beware_planks_m_0.geometry}
                    material={materials.planks_m}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/jims_haunted_home_gym.glb");

export default HauntedHouse;
