/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MihaiZ (https://sketchfab.com/MihaiZ)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mayan-pyramid-d1d0ecb14fda4d9a999548dd883e064b
Title: Mayan Pyramid
*/

import React, { useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Pyramid = (props) => {
  const { nodes, materials } = useGLTF("/mayan_pyramid.glb");

  const pyramidRef = useRef();
  // const { position } = useControls("Pyramid Controls", {
  //   position: [1, -3, 0],
  //   visible: true,
  // });
  const scroll = useScroll();

  console.log(pyramidRef);

  useFrame(({ camera }) => {
    if (pyramidRef.current) {
      // The Y position of the pyramid will change based on the scroll
      const scrollPosition = scroll.offset; // get the scroll position (0 to 1)

      pyramidRef.current.rotation.y = -1 + scrollPosition * 4; // Change the range as needed
      // pyramidRef.current.rotate.x = -1 + scrollPosition * 10; // Change the range as needed
      // pyramidRef.current.position.z = -1 + scrollPosition * 10; // Change the range as needed
      const pyramidPosition = pyramidRef.current.position;
      camera.position.set(
        scrollPosition * 8,
        scrollPosition * 0.1,
        scrollPosition * 0.1
      ); // Set camera position

      camera.lookAt(pyramidPosition); // Make camera look at the pyramid
    }
  });

  return (
    <group {...props} dispose={null} ref={pyramidRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Smooth_Sandstone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Sandstone_Bricks}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Stairs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Chamber}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.Top_Tile}
      />
    </group>
  );
};

useGLTF.preload("/mayan_pyramid.glb");

export default Pyramid;
